### ISSUE TITLE
Error: could not find function "ordiselect"

### ISSUE THREAD

**Issue by ninadesianti** [fvlampe/goeveg#6]
I tried to select species to be displayed on the NMDS plot. But the ordiselect function from goeveg package does not work. What did happen? What is wrong with my code? 

Below is the detail of the error messages:

> install.packages("goeveg")
Installing package into ‘C:/Users/nd425/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
also installing the dependencies ‘spam’, ‘maps’, ‘fields’

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/spam_1.4-0.zip'
Content type 'application/zip' length 1872116 bytes (1.8 MB)
downloaded 1.8 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/maps_3.1.1.zip'
Content type 'application/zip' length 3612141 bytes (3.4 MB)
downloaded 3.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/fields_8.4-1.zip'
Content type 'application/zip' length 3585127 bytes (3.4 MB)
downloaded 3.4 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/goeveg_0.2.0.zip'
Content type 'application/zip' length 52349 bytes (51 KB)
downloaded 51 KB

package ‘spam’ successfully unpacked and MD5 sums checked
package ‘maps’ successfully unpacked and MD5 sums checked
package ‘fields’ successfully unpacked and MD5 sums checked
package ‘goeveg’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\nd425\AppData\Local\Temp\RtmpS4JBQt\downloaded_packages
> limit12 <- ordiselect(specnmds, ord, ablim=0.3, fitlim=0.6, choices=c(1,2), method="vars", env=env.keep)
Error: could not find function "ordiselect"
> install.packages("goeveg")
Installing package into ‘C:/Users/nd425/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/goeveg_0.2.0.zip'
Content type 'application/zip' length 52349 bytes (51 KB)
downloaded 51 KB

package ‘goeveg’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\nd425\AppData\Local\Temp\RtmpS4JBQt\downloaded_packages
> limit <- ordiselect(specnmds, ord, ablim = 0.3, fitlim = 0.6, choices = c(1, 2),
+            method = "axes", env, p.max = 0.05, freq = FALSE)
Error: could not find function "ordiselect"

**Comment by ninadesianti** [comment]
I copy the ordiselect function from https://github.com/fgoral/goeveg/blob/3290fd4d02a27ae6240c14d1e204dfc71bb0892b/R/ordiselect.r and run it. It works! Here's the detail:

> ordiselect <-  function(matrix, ord, ablim = 1, fitlim = 1, choices = c(1,2), method = "axes", env, freq = FALSE) {
> -     if(!is.data.frame(matrix)) {
> -         matrix <- data.frame(matrix)
> -     }
> -   
> -     if(freq == F) {
> -         abund <- apply(matrix, 2, sum)
> -     } else {
> -         abund <- apply(matrix>0, 2, sum)
> -     }
> -   
> -     if(method == "axes") {
> -   
> -         scores <- data.frame(scores(ord, display="species", choices=choices))
> -         scores1 <- scores[,1]
> -         scores2 <- scores[,2]
> -   
> -         rownames(scores[abund >= quantile(abund, 1 - ablim) &
> -                             (scores1 >= quantile(scores1, 1-0.5*fitlim) |
> -                                  scores1 <= quantile(scores1,0.5*fitlim) |
> -                                  scores2 >= quantile(scores2, 1-0.5*fitlim) |
> -                                  scores2 <= quantile(scores2,0.5*fitlim))
> -                         ,])
> -   
> -     }  else if(method=="vars") {
> -   
> -         if(class(env) != "envfit") {
> -             print("FATAL: Fitted environmental variables are no result of envfit()")
> -         } else {
> -   
> -             scores_spec <- data.frame(scores(ord, display="species", choices=choices))
> -   
> -             sig <- env$vectors$pvals
> -             scores_env <- data.frame(scores(env, display="vectors"))
> -             scores_env <- scores_env[sig<0.05,]
> -   
> -             if(nrow(scores_env) == 0) {
> -   
> -                 print("WARNING: No significant environmental variables. Only abundance limit used for selection.")
> -   
> -                 names(abund[abund >= quantile(abund, 1 - ablim)])
> -   
> -             } else if(nrow(scores_env) == 1) {
> -   
> -                 print("WARNING: Only 1 significant environmental variable. Only abundance limit used for selection.")
> -   
> -                 names(abund[abund >= quantile(abund, 1 - ablim)])
> -   
> -             } else {
> -   
> -                 euclid<-data.frame(rdist(scores_spec, scores_env))
> -                 names(euclid)<-rownames(scores_env)
> -                 rownames(euclid)<-names(matrix)
> -   
> -                 best_fit<-euclid[abund > quantile(abund, 1 - ablim) &
> -                                      (euclid <= quantile(unlist(euclid), 0.5*fitlim) |
> -                                           euclid >= quantile(unlist(euclid), 1-0.5*fitlim)),]
> -                 rownames(best_fit[complete.cases(best_fit),])
> -   
> -             }
> -         }
> -     }  else {
> -         print("FATAL: Selected Method unknown")
> -     }
> - }
> 
> limit <- ordiselect(specnmds, ord, ablim = 0.3, fitlim = 0.6, choices = c(1, 2),
> -            method = "axes", env, p.max = 0.05, freq = FALSE)
>   Error in ordiselect(specnmds, ord, ablim = 0.3, fitlim = 0.6, choices = c(1,  : 
>   unused argument (p.max = 0.05)
>   limit <- ordiselect(specnmds, ord, ablim = 0.3, fitlim = 0.6, choices = c(1, 2),
> -            method = "axes", freq = FALSE)
>   limit
>   [1] "ACHNflex" "ACHNlemm" "ACHNminu" "ACHNsubm" "AMPHadum" "AMPHalla" "AMPHline"
>   [8] "AMPHpedi" "AMPHsp1"  "AMPHsp3"  "AMPHsp4"  "AMPHsp6"  "ANAUbalt" "ANORvort"
>   [15] "BERKscop" "BROCbroc" "CATEadha" "CHAEspp"  "CHAMsp4"  "COCCbrev" "COCCcfsc"
>   [22] "COCCdisc" "COCCpelt" "COCCpetd" "COCCstau" "CRATsp1"  "CYCLgrac" "CYCLmari"
>   [29] "CYCLstri" "CYMAbelg" "DELPminu" "DENTsubt" "EUNOsp1"  "FALLaequ" "FALLamph"
>   [36] "FALLmarg" "FALLpygm" "FALLtene" "FRAGbron" "FRAGcass" "FRAGcfca" "FRAGfame"
>   [43] "FRAGgeda" "FRAGguen" "FRAGsp1"  "FRAGsp3"  "GRAMocea" "GYROfasc" "GYROmacr"
>   [50] "GYROtenu" "HALAacut" "HALAapon" "HALAcoff" "HYALscot" "LUTImuti" "MELOnumm"
>   [57] "MINIspp"  "NAVIcfko" "NAVIcfmi" "NAVIcftr" "NAVIcfve" "NAVIcinc" "NAVIdigi"
>   [64] "NAVIdire" "NAVIgreg" "NAVIjons" "NAVImicr" "NAVIphya" "NAVIphyl" "NAVIplat"
>   [71] "NAVIpseu" "NAVIs002" "NAVIs005" "NAVIs006" "NAVIs012" "NAVIs023" "NAVIs026"
>   [78] "NAVIs029" "NAVIs034" "NAVIs037" "NAVIs038" "NAVIs041" "NAVIs043" "NAVIs051"
>   [85] "NAVIs063" "NAVIs066" "NAVIs069" "NAVIs102" "NAVIs105" "NAVIs106" "NAVIs108"
>   [92] "NAVIs110" "NAVIs111" "NAVIs120" "NAVIsaco" "NAVIsali" "NAVItrio" "NITZcfro"
>   [99] "NITZclos" "NITZcoar" "NITZdist" "NITZeleg" "NITZlaev" "NITZmicr" "NITZpara"
>   [106] "NITZpusi" "NITZscal" "NITZsigm" "NITZsp1"  "OPEPsp12" "PARAsulc" "PINNquad"
>   [113] "PLANdepe" "PLANfreq" "PLANrodr" "PLANsp11" "PLANsp2"  "PSEUperm" "PSEUsopo"
>   [120] "PSEUsp02" "PSEUsubs" "RHOPmusc" "SEMIpusi" "SKELspp"  "STAFatom" "STAFexig"
>   [127] "TABUcfwa" "TABUfasc" "THALceda" "THALcf01" "THALecce" "THALleva" "THALnitz"
>   [134] "THALoest" "THALpros" "THALweis" "TRYBsp3"

**Comment by fvlampe** [comment]
if the function was not found: did you load the package after installing? in don't find this in your code:
 `library(goeveg)`

**Comment by fvlampe** [comment]
As the function works, I think the topic can be closed.

**Comment by ninadesianti** [comment]
My bad, it works fine. Sorry for the very late response.
