### ISSUE TITLE
Error in library(goeveg) - no package called ‘spam’

### ISSUE THREAD

**Issue by Mathildebd** [fvlampe/goeveg#7]
Hi,

I cannot install this package (goeveg), see error message below:

`install.packages("goeveg")`

> Installing package into ‘C:/Users/Botany/Documents/R/win-library/3.3’
> (as ‘lib’ is unspecified)
> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.3/goeveg_0.3.0.zip'
> Content type 'application/zip' length 54426 bytes (53 KB)
> downloaded 53 KB
> 
> package ‘goeveg’ successfully unpacked and MD5 sums checked
> 
> The downloaded binary packages are in
> 	C:\Users\Botany\AppData\Local\Temp\Rtmpy47iHF\downloaded_packages

`library(goeveg)`

> Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
>   there is no package called ‘spam’
> Error: package or namespace load failed for ‘goeveg’

Am I doing something obvious wrong or is there a bug with the package?

Best wishes,
Mathilde

**Comment by fvlampe** [comment]
hmm, I find the 'spam' package as dependency of the required 'fields' package (which should therefore install automatically). Is it installed?
May try also to install the newest 'goeveg' version 0.3.2. from github, as there was a wrong code concerning external package functions in version 0.3.0 leading to some errors. I'll try to put that new version on CRAN soon.

**Comment by Mathildebd** [comment]
Okay, thank you for you answer.


I copy pasted the function from GitHub into my R script and it works! [😊]


Best wishes,

Mathilde



________________________________
Fra: fgoral <notifications@github.com>
Sendt: 17. januar 2017 16:34
Til: fgoral/goeveg
Cc: Mathildebd; Author
Emne: Re: [fgoral/goeveg] Error in library(goeveg) - no package called ‘spam’ (#7)


hmm, I find the 'spam' package as dependency of the required 'fields' package (which should therefore install automatically). Is it installed?
May try also to install the newest 'goeveg' version 0.3.2. from github, as there was a wrong code concerning external package functions in version 0.3. leading to some errors. I'll try tu put that version on CRAN soon.
